### ISSUE TITLE
CRUD - GET

### ISSUE THREAD

**Issue by dorianeGH** [WildCodeSchool/hdrain-api-lyon-js-react-march21#5]
## Story

As a user I want to get the data

## Criteria & special considerations

- Use a router

4 different routes: 
- /locations
- /locations/:locationId/
- /locations/:locationId/sensors
- /locations/:locationId/sensors/:sensorId/experiments/:experimentId

NB : N'envoyer que la liste de locations pas le reste (pas les sensors, experiments...)
NB : créer une BDD "test"
## Integration test scenario

- Test using postman / insomnia all the routes

## Acceptance Criteria

- The received object is as follows : 
{
TBD
}

## Tasks

- [] Create GET /locations
- [] Create GET /locations/:locationId/sensors
- [] Create GET /locations/:locationId/sensors/:sensorId
