### ISSUE TITLE
CRUD - PATCH

### ISSUE THREAD

**Issue by dorianeGH** [WildCodeSchool/hdrain-api-lyon-js-react-march21#6]
## Story

Set up a PATCH route in order for HD Rain server to update data into our MongoDB

## Criteria & special considerations

- Use a router
4 different routes: 
- /locations
- /locations/:locationId/
- /locations/:locationId/sensors
- /locations/:locationId/sensors/:sensorId/experiments ??

## Integration test scenario

- Test your route on insomnia / postman

## Integration test scenario

- Test using postman / insomnia all the routes

## Acceptance Criteria

- The received object is as follows : 
{
TBD
}

## Tasks
- [] Send req.body to the MongoDB
- [] Create PATCH /locations
- [] Create PATCH /locations/:locationId/sensors
- [] Create PATCH /locations/:locationId/sensors/:sensorId
